# Continuous Deployment workflow: Release & Publish to GitHub Packages
name: Publish Packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - 'renovate.json'

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node

  publish:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@lacolaco'
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
      - name: Publish to GitHub Packages
        run: pnpm publish --no-git-checks --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
